apiVersion: v1
kind: Service
metadata:
  name: salle-reservation-service
spec:
  selector:
    app: salle-reservation
  ports:
    - protocol: TCP
      port: 8002         
      targetPort: 8002   
  type: ClusterIP
