apiVersion: v1
kind: Service
metadata:
  name: salle-service
spec:
  selector:
    app: salle-service  
  ports:
    - protocol: TCP
      port: 8001         
      targetPort: 8001   
  type: ClusterIP
